package Oso;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ijash
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuProduk = new javax.swing.JMenuItem();
        menuPegawai = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenuItem();
        menuKategori = new javax.swing.JMenuItem();
        menuPesanan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuFile.setText("File");

        menuLogOut.setText("LogOut");
        menuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogOutActionPerformed(evt);
            }
        });
        menuFile.add(menuLogOut);

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        menuFile.add(menuKeluar);

        jMenuBar1.add(menuFile);

        menuMaster.setText("Master");

        menuProduk.setText("Produk");
        menuProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdukActionPerformed(evt);
            }
        });
        menuMaster.add(menuProduk);

        menuPegawai.setText("Pegawai");
        menuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPegawaiActionPerformed(evt);
            }
        });
        menuMaster.add(menuPegawai);

        menuSupplier.setText("Supplier");
        menuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSupplierActionPerformed(evt);
            }
        });
        menuMaster.add(menuSupplier);

        menuKategori.setText("Kategori");
        menuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKategoriActionPerformed(evt);
            }
        });
        menuMaster.add(menuKategori);

        jMenuBar1.add(menuMaster);

        menuPesanan.setText("Pesanan");
        menuPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesananActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuPesanan);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 410, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Form_Login Login = new Form_Login();
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);
    }//GEN-LAST:event_menuLogOutActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdukActionPerformed
        // TODO add your handling code here:
        Form_Produk produk = new Form_Produk();
        produk.setLocationRelativeTo(null);
        produk.setVisible(true);
    }//GEN-LAST:event_menuProdukActionPerformed

    private void menuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPegawaiActionPerformed
        // TODO add your handling code here:
        Form_Pegawai pegawai = new Form_Pegawai();
        pegawai.setLocationRelativeTo(null);
        pegawai.setVisible(true);
    }//GEN-LAST:event_menuPegawaiActionPerformed

    private void menuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupplierActionPerformed
        // TODO add your handling code here:
        Form_Supplier supplier = new Form_Supplier();
        supplier.setLocationRelativeTo(null);
        supplier.setVisible(true);
    }//GEN-LAST:event_menuSupplierActionPerformed

    private void menuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKategoriActionPerformed
        // TODO add your handling code here:
        Form_Kategori kategori = new Form_Kategori();
        kategori.setLocationRelativeTo(null);
        kategori.setVisible(true);
    }//GEN-LAST:event_menuKategoriActionPerformed

    private void menuPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesananActionPerformed
        // TODO add your handling code here:
        Form_Pesanan pesanan = new Form_Pesanan();
        pesanan.setLocationRelativeTo(null);
        pesanan.setVisible(true);
    }//GEN-LAST:event_menuPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuKategori;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuLogOut;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPegawai;
    private javax.swing.JMenu menuPesanan;
    private javax.swing.JMenuItem menuProduk;
    private javax.swing.JMenuItem menuSupplier;
    // End of variables declaration//GEN-END:variables
}
